#!/usr/bin/env python3
"""Hot-path discipline, checked by the compiler: what the render path calls that can block.

`MoonModule::tick/tick20ms/tick1s` carry `MM_NONBLOCKING` (platform.h). Clang 20+ then verifies
under `-Wfunction-effects` that nothing they reach allocates or blocks — TRANSITIVELY, through
the whole call graph — the half a regex over the tick body cannot see, being blind to what its
callees do. (It replaced exactly such a lint, check_hotpath.py.)

Reports unique SITES. A header included by N translation units yields N copies of the same
warning, so a raw build prints ~1350 lines for ~175 real findings; deduplicating on
(file, line) is most of this script's value.

Not a gate. `-Wno-error=function-effects` in CMakeLists keeps the build green while these are
triaged; each finding is a judgement — fix it, annotate the callee, or accept it with a scoped
reason — and the answer differs per site.

Usage:
  uv run moondeck/check/check_nonblocking.py            # summary by callee, then every site
  uv run moondeck/check/check_nonblocking.py --module AudioService
"""

import argparse
import collections
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_clang_query  # noqa: E402  — the module→files resolver, one owner
import check_clang_tidy   # noqa: E402  — build-dir resolution, one owner

# `path:line:col: warning: <msg> [-Wfunction-effects]`
_WARN = re.compile(r"^(?P<file>\S+?):(?P<line>\d+):(?P<col>\d+): warning: "
                   r"(?P<msg>.*?) \[-Wfunction-effects\]")
_CALLEE = re.compile(r"non-'nonblocking' function '(?P<name>[^']+)'")

# Clang follows each warning with a `note:` saying WHY the callee is not nonblocking — either it
# reaches another blocking function, or it has a construct that rules it out (a static local
# needs a guard variable and a lock). That note is the difference between "this line is flagged"
# and "here is what to fix", so it becomes the WHY column.
_NOTE = re.compile(r"note: function cannot be inferred 'nonblocking' because it "
                   r"(?:calls non-'nonblocking' function '(?P<via>[^']+)'|(?P<reason>.+))")

MAX_ROWS = 40

# Shown when clang gave no root cause (a leaf it could not look inside). Named rather than
# inlined: a backslash escape inside an f-string EXPRESSION is a syntax error before 3.12.
NO_CAUSE = "\u2014"

# The known set, frozen — a READING AID, not a gate. Every finding stays in the report (a report
# shows the real situation); the baseline only marks which ones are NEW since it was taken, so
# ~50 known entries do not bury the one that appeared this week.
#
# Deliberately does not fail a build. A new blocking call may be entirely legitimate — a driver
# that genuinely must wait for hardware — and a hard failure would push someone to suppress it
# under time pressure, which is precisely what this report exists to prevent. The tools report;
# the human judges.
#
# Keyed on (file, callee) rather than line number, so the entry survives edits above it. Losing
# the line means two calls to the same function in one file collapse to one entry — acceptable:
# the question this answers is "is this a NEW kind of blocking call", not "how many".
BASELINE = ROOT / "docs" / "metrics" / "hotpath-baseline.txt"


def read_baseline():
    """The frozen (file, callee) pairs. Absent file = nothing frozen, everything is new."""
    if not BASELINE.exists():
        return set()
    out = set()
    for line in BASELINE.read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        if "\t" in line:
            f, callee = line.split("\t", 1)
            out.add((f.strip(), callee.strip()))
    return out


def write_baseline(rows):
    lines = [
        "# Hot-path baseline — the blocking calls reachable from tick/tick20ms/tick1s today.",
        "#",
        "# Generated by `uv run moondeck/check/check_nonblocking.py --baseline`. Format is",
        "# `<file>\\t<callee>`; `#` starts a comment. Keyed on file+callee, NOT line, so an entry",
        "# survives edits above it.",
        "#",
        "# A line here means KNOWN AND BACKLOGGED, not acceptable — see backlog-core.md",
        "# 'move blocking work off the render callbacks'. The list only shrinks: move the work",
        "# off the render path, delete the line. Adding a line means admitting a new blocking",
        "# call on the render path, which is what this exists to prevent.",
        "",
    ]
    for r in sorted({(x["file"], x["callee"]) for x in rows}):
        lines.append(f"{r[0]}\t{r[1]}")
    BASELINE.write_text("\n".join(lines) + "\n", encoding="utf-8")

# The enclosing method of a call site. Clang names the call and the callee but NOT the function
# they sit in, and that is the column that says which tick tier is affected — tick() every frame
# vs tick1s() once a second is an order of magnitude difference in what a blocking call costs.
# Walked backwards from the site to the nearest definition at class-member indent.
# Excludes control-flow keywords, which otherwise match `if (...) {` and report `IN: if`.
# Handles both in-class definitions and out-of-line `void Foo::tick() {`.
_KEYWORDS = ("if", "for", "while", "switch", "catch", "else", "do", "return")
_DEF = re.compile(r"^(?P<indent>\s*)(?:[\w:<>,&*\s]+?\s)?(?:(?P<cls>\w+)::)?(?P<name>\w+)\s*"
                  r"\([^;]*\)\s*(?:const\s*)?(?:MM_NONBLOCKING\s*)?(?:override\s*)?"
                  r"(?:noexcept\s*)?\{")

# Which tick tier a function belongs to, once resolved through the enclosing method.
TIERS = ("tick", "tick20ms", "tick1s")


def enclosing_function(rel_path, line, _cache={}):
    """The method a call site sits in, or "" when it cannot be determined."""
    src = _cache.get(rel_path)
    if src is None:
        f = ROOT / rel_path
        src = _cache[rel_path] = (f.read_text(encoding="utf-8", errors="replace").split("\n")
                                  if f.exists() else [])
    for i in range(min(line, len(src)) - 1, -1, -1):
        m = _DEF.match(src[i])
        if m and len(m.group("indent")) <= 4 and m.group("name") not in _KEYWORDS:
            return m.group("name")
    return ""


def build_output(build_dir, clean=True):
    """A full rebuild's warnings, or None if the build failed.

    `--clean-first` because an incremental build only recompiles what changed, and a cached TU
    prints nothing — which would read as "no findings". Likewise a FAILED build produces partial
    output: returning it would report a small number as if the tree were nearly clean, the same
    silent-zero trap the other checks guard against.
    """
    cmd = ["cmake", "--build", str(build_dir)] + (["--clean-first"] if clean else [])
    proc = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, check=False)
    out = proc.stdout + proc.stderr
    if proc.returncode != 0:
        errors = [line for line in out.splitlines() if ": error:" in line]
        print(f"Build FAILED (exit {proc.returncode}) — findings would be incomplete.",
              file=sys.stderr)
        for error_line in errors[:5]:
            print(f"  {error_line.replace(str(ROOT) + '/', '')}", file=sys.stderr)
        return None

    # FAIL CLOSED. -Wfunction-effects exists only on Clang 20+; CMake silently omits the flag
    # on anything else, and this script would then report "0 findings" from a build that never
    # ran the check — indistinguishable from a clean tree. A zero is only trustworthy if the
    # warning is actually enabled, so say so instead of reporting a comfortable number.
    if clean and "[-Wfunction-effects]" not in out:
        print("No -Wfunction-effects diagnostics in the build output.\n"
              "That means either the tree really is clean, or the compiler does not support the\n"
              "warning (it needs Clang 20+; CMake omits it silently otherwise). Check with:\n"
              f"  grep -n 'Wfunction-effects' {(ROOT / 'CMakeLists.txt').relative_to(ROOT)}\n"
              "  cmake --build <dir> --clean-first 2>&1 | grep -c function-effects",
              file=sys.stderr)
        return None
    return out


def collect(out):
    """Unique findings keyed on (file, line, col), each with the root cause clang gives.

    A warning line names the call; the `note:` line that follows names why that callee blocks.
    Both are needed to act on a finding, so they are carried together.
    """
    rows, last = {}, None
    for line in out.splitlines():
        clean = line.replace(str(ROOT) + "/", "")
        m = _WARN.match(clean)
        if m:
            f = m["file"]
            last = None
            if f.startswith(("src/", "test/")):
                c = _CALLEE.search(m["msg"])
                key = (f, int(m["line"]), int(m["col"]))
                # Two violation kinds: a call to something that blocks, or a construct that
                # blocks by itself (a static local needs a guard variable and a one-time lock).
                # The second has no callee, so name the construct instead of truncating the
                # warning text into the CALLS column.
                rows.setdefault(key, {
                    "file": f, "line": int(m["line"]),
                    "callee": c["name"] if c else "(static local variable)",
                    "why": "" if c else "guard variable + one-time lock on first use",
                    "fn": enclosing_function(f, int(m["line"])),
                })
                last = key
            continue
        # The note belongs to the warning just above it.
        if last:
            n = _NOTE.search(clean)
            if n and not rows[last]["why"]:
                rows[last]["why"] = (f"calls {n['via']}" if n["via"]
                                     else n["reason"].strip().rstrip("."))
    return sorted(rows.values(), key=lambda r: (r["file"], r["line"]))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--module", help="Only findings in this module's source files.")
    ap.add_argument("--baseline", action="store_true",
                    help="Rewrite the frozen set from today's findings.")
    ap.add_argument("--incremental", action="store_true",
                    help="Skip the clean rebuild — only files that changed are recompiled, so "
                         "this reports on THOSE. For a gate that asks 'did this change add a "
                         "blocking call', not for the full picture.")
    args = ap.parse_args()

    build_dir = check_clang_tidy._host_build_dir()
    if not (build_dir / "CMakeCache.txt").exists():
        print(f"No build in {build_dir.relative_to(ROOT)} — run "
              f"`uv run moondeck/build/build_desktop.py` first.", file=sys.stderr)
        return 2

    out = build_output(build_dir, clean=not args.incremental)
    if out is None:
        return 2
    rows = collect(out)

    if args.baseline:
        write_baseline(rows)
        print(f"Baseline written: {len({(r['file'], r['callee']) for r in rows})} "
              f"(file, callee) pairs frozen in {BASELINE.relative_to(ROOT)}")
        return 0

    # Mark what is new since the baseline. Not a filter — everything is still shown.
    # Existence, not emptiness: an EMPTY baseline is a deliberate "nothing is known-good", so
    # every finding is new. Only a MISSING file means "no baseline taken yet".
    has_baseline = BASELINE.exists()
    known = read_baseline()
    for r in rows:
        r["new"] = has_baseline and (r["file"], r["callee"]) not in known

    if args.module:
        only = check_clang_query.module_files(args.module)
        if not only:
            print(f"No source files for module '{args.module}'.", file=sys.stderr)
            return 2
        print(f"Filtered to {args.module}: {', '.join(only)}\n")
        rows = [r for r in rows if r["file"] in only]

    n_new = sum(1 for r in rows if r.get("new"))
    print(f"{len(rows)} call(s) from the render path that can block or allocate.")
    if has_baseline:
        print(f"{n_new} NEW since the baseline ({len(known)} known, backlogged as architecture "
              f"work)." if n_new else
              f"None new since the baseline — all {len(known)} are known and backlogged.")
    else:
        print("No baseline yet: run with --baseline to freeze today's set, so a future run can "
              "show what is new.")
    if not rows:
        print("\nNone. \u2713  (If that seems wrong, confirm the build actually recompiled \u2014 a "
              "cached TU prints no warnings.)")
        return 0

    # Split by tick tier: tick() runs every frame, tick1s() once a second, so the same blocking
    # call costs roughly two orders of magnitude more in one than the other (50/s vs 1/s).
    # Pooling them hides that.
    def tier_of(r):
        return r["fn"] if r["fn"] in TIERS else "other"

    def table(title, subset, note):
        if not subset:
            return
        callee_w = min(max(len(r["callee"]) for r in subset), 36)
        fn_w = min(max(len(r["fn"] or "?") for r in subset), 18)
        why_w = min(max((len(r["why"]) for r in subset), default=0), 44) or 1
        loc_w = min(max(len(f"{r['file']}:{r['line']}") for r in subset), 44)

        def clip(s, w):
            return s if len(s) <= w else s[: w - 1] + "\u2026"

        print(f"\n{title} \u2014 {len(subset)}   ({note})")
        print(f"      {'CALLS':<{callee_w}}  {'IN':<{fn_w}}  {'WHY IT BLOCKS':<{why_w}}  FILE:LINE")
        print(f"      {'-' * callee_w}  {'-' * fn_w}  {'-' * why_w}  {'-' * loc_w}")
        for r in subset[:MAX_ROWS]:
            why = r["why"] or NO_CAUSE
            mark = "NEW " if r.get("new") else "    "
            print(f"  {mark}{clip(r['callee'], callee_w):<{callee_w}}  "
                  f"{clip(r['fn'] or '?', fn_w):<{fn_w}}  "
                  f"{clip(why, why_w):<{why_w}}  "
                  f"{r['file']}:{r['line']}")
        if len(subset) > MAX_ROWS:
            print(f"  \u2026 {len(subset) - MAX_ROWS} more. Use --module <name> to scope.")

    for tier, note in (("tick", "every frame \u2014 the hot path"),
                       ("tick20ms", "50x a second"),
                       ("tick1s", "once a second \u2014 sub-hot path"),
                       ("other", "reached from a tick, tier not resolved")):
        table(tier + "()" if tier != "other" else "OTHER",
              [r for r in rows if tier_of(r) == tier], note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
